#!/bin/bash
esearch -db sra -query ERS1351147 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1351147
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1351147 -n snp.txt -d out/ERS1351147 -e jlever@bcgsc.ca -t 1 -p 1
