#!/bin/bash
esearch -db sra -query ERS1349298 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1349298
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1349298 -n snp.txt -d out/ERS1349298 -e jlever@bcgsc.ca -t 1 -p 1
