#!/bin/bash
esearch -db sra -query ERS1348581 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1348581
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1348581 -n snp.txt -d out/ERS1348581 -e jlever@bcgsc.ca -t 1 -p 1
