#!/bin/bash
esearch -db sra -query ERS1351601 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1351601
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1351601 -n snp.txt -d out/ERS1351601 -e jlever@bcgsc.ca -t 1 -p 1
