#!/bin/bash
esearch -db sra -query ERS1349709 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1349709
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1349709 -n snp.txt -d out/ERS1349709 -e jlever@bcgsc.ca -t 1 -p 1
