#!/bin/bash
esearch -db sra -query ERS1351295 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1351295
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1351295 -n snp.txt -d out/ERS1351295 -e jlever@bcgsc.ca -t 1 -p 1
