#!/bin/bash
esearch -db sra -query ERS1349751 | esummary | xtract -pattern DocumentSummary -ACC @acc -block DocumentSummary -element "&ACC" | cut -f 5 > acc/ERS1349751
bash /home/ubuntu/test/PSST/psst_2.sh -s acc/ERS1349751 -n snp.txt -d out/ERS1349751 -e jlever@bcgsc.ca -t 1 -p 1
